In [1]:
#Create a null vector of size 10 but the fifth value which is 1

import numpy as np
vector = np.zeros(10)
vector[4]=1
print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [3]:
#2. Create a vector with values ranging from 10 to 49.

vector_2 = np.arange(10,50)
print(vector_2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [4]:
#3. Create a 3x3 matrix with values ranging from 0 to 8

vector_3 = np.arange(0,9)
matrix = vector_3.reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [5]:
#4. Find indices of non-zero elements from [1,2,0,0,4,0]

arr = [1,2,0,0,4,0]
indices = np.nonzero(arr)
print(indices)

(array([0, 1, 4], dtype=int64),)


In [8]:
# 5. Create a 10x10 array with random values and find the minimum and maximum values.

arr_5 = np.random.random((10,10))
#print(arr_5)
max_value = arr_5.max()
min_value = arr_5.min()
print(f"Maximum value : {max_value}")
print(f"Minimum value : {min_value}")


Maximum value : 0.9951591567343935
Minimum value : 0.0076542035504154615


In [14]:
#6. Create a random vector of size 30 and find the mean value.

vector_6 = np.random.random(30)
mean = vector_6.mean()
print(f"Mean Value : {mean}")

Mean Value : 0.528840362636973
